language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower grunt-cli'
  - 'npm install karma'
  - 'bower install angular'
  - 'bower install angular-mocks'
script:
  - ./node_modules/karma/bin/karma start karma.config.js --no-auto-watch --single-run --reporters=dots --browsers=Phantom